name: Delete preview stack on PR close

on:
  pull_request:
    types:
    - closed

jobs:
  delete-stack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install root
      run: npm ci

    - name: Setup AWS Credentials
      run: |
        mkdir ~/.aws
        echo "[myapp_dev]
        aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials

    - name: Delete PR preview stack
      run: npm run remove-stack:dev -- --gitHubPullRequestBranch=${{ github.head_ref }}
    