name: Delete preview stack on PR close

on:
  pull_request:
    types:
    - closed

jobs:
  delete-stack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install root
      run: npm ci

    - name: Delete PR preview stack
      run: npm run remove-stack:dev -- --gitHubPullRequestBranch=${{ github.head_ref }}
    